export const chefs = [
  {
    id: 1,
    username: "chef_john",
    email: "john@example.com",
    password_hash: "hashed_password_1",
    profile_image_url: "https://example.com/chef_john.jpg",
    bio: "Passionate chef with years of experience in Italian cuisine.",
    country: "Italy",
  },
  {
    id: 2,
    username: "chef_emily",
    email: "emily@example.com",
    password_hash: "hashed_password_2",
    profile_image_url: "https://example.com/chef_emily.jpg",
    bio: "Specializing in French pastries and desserts.",
    country: "France",
  },
  {
    id: 3,
    username: "chef_michael",
    email: "michael@example.com",
    password_hash: "hashed_password_3",
    profile_image_url: "https://example.com/chef_michael.jpg",
    bio: "Celebrity chef known for his fusion cuisine and innovative recipes.",
    country: "United States",
  },
  {
    id: 4,
    username: "chef_sophia",
    email: "sophia@example.com",
    password_hash: "hashed_password_4",
    profile_image_url: "https://example.com/chef_sophia.jpg",
    bio: "Expert in traditional Japanese cooking techniques.",
    country: "Japan",
  },
  {
    id: 5,
    username: "chef_antonio",
    email: "antonio@example.com",
    password_hash: "hashed_password_5",
    profile_image_url: "https://example.com/chef_antonio.jpg",
    bio: "Master of Mediterranean cuisine, bringing the flavors of Greece and Spain to your kitchen.",
    country: "Spain",
  },
];
