export const likes = [
  { like_id: 1, recipe_id: 1, liker_id: 2 },
  { like_id: 2, recipe_id: 2, liker_id: 3 },
  { like_id: 3, recipe_id: 3, liker_id: 4 },
  { like_id: 4, recipe_id: 4, liker_id: 5 },
  { like_id: 5, recipe_id: 5, liker_id: 1 },
  { like_id: 6, recipe_id: 6, liker_id: 2 },
  { like_id: 7, recipe_id: 7, liker_id: 3 },
  { like_id: 8, recipe_id: 8, liker_id: 4 },
  { like_id: 9, recipe_id: 9, liker_id: 5 },
  { like_id: 10, recipe_id: 10, liker_id: 1 },
  { like_id: 11, recipe_id: 11, liker_id: 2 },
  { like_id: 12, recipe_id: 12, liker_id: 3 },

  { like_id: 14, recipe_id: 14, liker_id: 5 },
  { like_id: 15, recipe_id: 1, liker_id: 2 },
  { like_id: 16, recipe_id: 6, liker_id: 3 },
  { like_id: 17, recipe_id: 7, liker_id: 4 },
  { like_id: 18, recipe_id: 8, liker_id: 5 },
  { like_id: 19, recipe_id: 1, liker_id: 4 },
  { like_id: 20, recipe_id: 2, liker_id: 2 },
];
